# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-19 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('DV', 'Devotional'), ('SC', 'Study Cicle')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityTypeName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoreActivityTracker.ActivityType')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('code', models.CharField(max_length=3)),
                ('iso_2', models.CharField(max_length=2)),
                ('iso_3', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='DeclarationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declaration_status', models.CharField(choices=[('BA', "Baha'i"), ('FO', 'Friend of Faith'), ('DO', "Don't know"), ('SP', 'Spectator')], default='DO', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='DeclarationStatusName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('declaration_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoreActivityTracker.DeclarationStatus')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=35)),
                ('address_line_1', models.CharField(max_length=100)),
                ('address_line_2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state_or_province', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=35)),
                ('latitude_degrees', models.FloatField()),
                ('longitude_degrees', models.FloatField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoreActivityTracker.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=35)),
                ('declaration_status_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoreActivityTracker.DeclarationStatusName')),
            ],
        ),
        migrations.CreateModel(
            name='SpokenLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_name', models.CharField(max_length=50)),
                ('iso_639_2_code', models.CharField(max_length=3)),
                ('iso_639_1_code', models.CharField(max_length=2)),
                ('biblio_or_term', models.CharField(max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='declarationstatusname',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoreActivityTracker.SpokenLanguage'),
        ),
        migrations.AddField(
            model_name='activitytypename',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoreActivityTracker.SpokenLanguage'),
        ),
        migrations.AddField(
            model_name='activityreport',
            name='activity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoreActivityTracker.ActivityTypeName'),
        ),
        migrations.AddField(
            model_name='activityreport',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoreActivityTracker.Location'),
        ),
        migrations.AddField(
            model_name='activityreport',
            name='persons',
            field=models.ManyToManyField(to='CoreActivityTracker.Person'),
        ),
    ]
