# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-01 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreActivityTracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spokenlanguage',
            name='biblio_or_term',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
